config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path
  resources :posts do
    resources :comments
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]



 root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments
  # belongs_to :user
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  # has_many :posts
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception

  add_flash_types :danger, :info, :warning, :success
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    # @comment = @post.comments.create(comment_params)
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  # private def comment_params
  #   params.require(:comment).permit(:name, :body)
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    #we want newer post to show on top so reverse the post order
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  #save posts, define a create method
  def create
    #first create post
    @post = Post.new(post_params)

    # if statement to control when to display error messages and to handle if save is successful
    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to @post
    else
      #we want to do a render instead of a redirect because a redirect will do a new http refresh if the post did not save and the user will loose all the content they put in the form.  Render new method keeps all content in place
      flash.now[:notice] = "Could not create new post, please try again"
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end


def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])
  if @post.update(params[:post].permit(:title, :body))
    flash[:notice] = "Post successfully updated"
    redirect_to @post
  else
    render 'edit'
  end
end


def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to root_path
end

  #We need to specify what paramaters we want to save so need to create a method because rails 4 and beyond security features requries you to explcitly say what parameters you want to allow so need a private method
  private
    def post_params
      params.require(:post).permit(:title, :body)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have logged in"
      redirect_to root_path
    else
      flash[:notice] = "Your username or password is incorret"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.notify_user(@user).deliver
      session[:user_id] = @user.id
      flash[:notice] = "Welcome To Anything Blog"
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end


  private
 #strong params
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<!-- the file to show the comments and how they will be structured-->
<!-- each comment is going to be inside of a comment -->


<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
</div>

app/views/comments/_comment_html.erb
<!-- the file to show the comments and how they will be structured-->
<!-- each comment is going to be inside of a comment -->


<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/dashing/dashboards/sample.html.erb
<% content_for :title do %>
  Kalier's dashboard
<% end %>

<div class="gridster">
  <ul>
    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="welcome" data-view="Text" data-title="Hello Curtis" data-text="This is your Dashboard For All Things Reffing." data-moreinfo="Protip: You can drag the widgets around!"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="synergy" data-view="Meter" data-title="Curtis Thoughts on Grapes" data-min="0" data-max="100"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="2">
      <div data-id="buzzwords" data-view="List" data-unordered="true" data-title="Buzzwords" data-moreinfo="# of times said around the office"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="valuation" data-view="Number" data-title="Current Valuation" data-moreinfo="In billions" data-prefix="$"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="convergence" data-view="Graph" data-title="Convergence" style="background-color:#ff9618"></div>
    </li>
  </ul>
  <center><div style="font-size: 12px">Try this: curl -X PUT 'http://<%= request.host %>:<%= request.port %>/dashing/widgets/welcome' -d "widget[text]=Dashing is awesome"</div></center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag 'favicon.ico' %>
  <!-- <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="theme-color" content="#ffffff"> -->

    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div id="sidebar">
      <!-- Add logo to sidebar navigation -->


      <!-- Add navigation links -->
      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %> </li>
         <li><a href="http://localhost:3000/dashing/dashboards">Dashboard</a></li>

      </ul>

      <ul>
        <li class="category">Social</li>
        <li><a href="https://twitter.com/GottaHaveTennis?lang=en">Twitter</a></li>
        <li><a href="https://www.instagram.com/tenniscrazy1/">Instagram</a></li>
        <li><a href="mailto:tenniscrazy1@gmail.com">Email</a></li>
      </ul>



      <!-- <p class="sign_in">Admin Login</p> -->
    </div>

    <div id="main_content">
      <div id="header">
      <p>Anything Blog</p>


        <div  class="buttons">
        <button class="button"><%= link_to "Register", new_user_path %></button>
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button">Log Out</button>

          <button class="button"><%= link_to "Login", new_session_path %></button>

        </div>
      </div>


    <!-- Add below text for a flash message if someone creates a post, sign-in or sign-out, it will say, you successfully created a new post -->
  <div id= "notice">
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  </div>

    <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/dashing/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= yield :title %></title>

    <%= javascript_include_tag 'dashing/application' %>
    <%= stylesheet_link_tag 'dashing/application' %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="icon" href="/favicon.ico">
  </head>
  <body>
    <div id="container">
      <%= yield %>
    </div>

    <% if Rails.env.development? %>
      <div id="saving-instructions">
        <p>Paste the following at the top of <i><%= params[:dashboard] %>.erb</i></p>
        <textarea id="gridster-code"></textarea>
      </div>
      <a href="#saving-instructions" id="save-gridster">Save this layout</a>
    <% end %>
  </body>
</html>

app/views/posts/_form.html.erb
<!-- rails is smart enough to tell if the form is for edit or new so you don't need :post, url: posts_path -->
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <div id="errors">
    <!-- pluralize is for anyting past a count of 1 it will automatically pluralize it or it will just be errlr -->
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>

    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>

     <p>
      <%= f.label :body %>
      <%= f.text_field :body %>
    </p>

     <p>
      <%= f.submit %>
    </p>

  <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
     <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <!-- this will link to post and put the post path -->
    <h2 class="title"><%=link_to post.title, post %></h2>
    <!-- use.strftime("%B, %d, %Y") to show actual date -->
    <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<%end %>

app/views/posts/new.html.erb
<div id="page_wrapper">


  <h1>New Post</h1>
     <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">

  <h1 class="title"><%= @post.title %></h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago | <%= link_to 'Edit', edit_post_path(@post) %>  | <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
  </p>

  <p  class="body"><%= @post.body %>
  </p>


<!-- ***************************** -->
<div id="comments">
    <!-- grabbing the _commnets.html.erb -->
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
<!-- ***************************** -->

    <!-- grabbing the _form.html.erb -->
    <h3>Add A Comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>

app/views/users/new.html.erb
 <div id="page_wrapper">
    <h1> Register </h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="errors">
    <!-- pluralize is for anyting past a count of 1 it will automatically pluralize it or it will just be errlr -->
      <h2><%= pluralize(@user.errors.count, "error") %> prevented this user from saving</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>

    <p>
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>

     <p>
      <%= f.label :password %><br>
      <%= f.password_field :password%>
    </p>

     <p>
      <%= f.submit %>
    </p>

  <% end %>

  </div>